/** 2025年時点で日常的に使われている代表的なプログラミング言語をchatGPTに列挙させたリスト */
export const popularLanguages = [
  { value: "Ada", label: "Ada" },
  { value: "Assembly", label: "Assembly" },
  { value: "Bash", label: "Bash" },
  { value: "C", label: "C" },
  { value: "C#", label: "C#" },
  { value: "C++", label: "C++" },
  { value: "COBOL", label: "COBOL" },
  { value: "CSS", label: "CSS" },
  { value: "Crystal", label: "Crystal" },
  { value: "Dart", label: "Dart" },
  { value: "Elixir", label: "Elixir" },
  { value: "Erlang", label: "Erlang" },
  { value: "F#", label: "F#" },
  { value: "Fortran", label: "Fortran" },
  { value: "Go", label: "Go" },
  { value: "Groovy", label: "Groovy" },
  { value: "Hack", label: "Hack" },
  { value: "Haskell", label: "Haskell" },
  { value: "HTML", label: "HTML" },
  { value: "Java", label: "Java" },
  { value: "JavaScript", label: "JavaScript" },
  { value: "Julia", label: "Julia" },
  { value: "Kotlin", label: "Kotlin" },
  { value: "Less", label: "Less" },
  { value: "Lua", label: "Lua" },
  { value: "MATLAB", label: "MATLAB" },
  { value: "Nim", label: "Nim" },
  { value: "Objective-C", label: "Objective-C" },
  { value: "OCaml", label: "OCaml" },
  { value: "Perl", label: "Perl" },
  { value: "PHP", label: "PHP" },
  { value: "PowerShell", label: "PowerShell" },
  { value: "Python", label: "Python" },
  { value: "R", label: "R" },
  { value: "Ruby", label: "Ruby" },
  { value: "Rust", label: "Rust" },
  { value: "Sass", label: "Sass" },
  { value: "Scala", label: "Scala" },
  { value: "Shell", label: "Shell" },
  { value: "Solidity", label: "Solidity" },
  { value: "SQL", label: "SQL" },
  { value: "Swift", label: "Swift" },
  { value: "Tcl", label: "Tcl" },
  { value: "TypeScript", label: "TypeScript" },
  { value: "VBA", label: "VBA" },
  { value: "VB.NET", label: "VB.NET" },
  { value: "Verilog", label: "Verilog" },
  { value: "VHDL", label: "VHDL" },
  { value: "Zig", label: "Zig" }
];

/** 2025年時点で日常的に使われている代表的なフレームワーク、ミドルウェア、ツールをchatGPTに列挙させたリスト */
export const popularFrameworksAndTools = [
  // フレームワーク
  { value: "Angular", label: "Angular" },
  { value: "ASPNetCore", label: "ASPNetCore" },
  { value: "Django", label: "Django" },
  { value: "Express", label: "Express" },
  { value: "Flask", label: "Flask" },
  { value: "Laravel", label: "Laravel" },
  { value: "NestJS", label: "NestJS" },
  { value: "Nextjs", label: "Nextjs" },
  { value: "Nuxtjs", label: "Nuxtjs" },
  { value: "Phoenix", label: "Phoenix" },
  { value: "React", label: "React" },
  { value: "RubyOnRails", label: "RubyOnRails" },
  { value: "SpringBoot", label: "SpringBoot" },
  { value: "Symfony", label: "Symfony" },
  { value: "Vuejs", label: "Vuejs" },

  // ミドルウェア（DBを除く）
  { value: "Apache", label: "Apache" },
  { value: "Docker", label: "Docker" },
  { value: "Elasticsearch", label: "Elasticsearch" },
  { value: "Kafka", label: "Kafka" },
  { value: "Kubernetes", label: "Kubernetes" },
  { value: "Nginx", label: "Nginx" },
  { value: "RabbitMQ", label: "RabbitMQ" },

  // ツール
  { value: "Backlog", label: "Backlog" },
  { value: "Bitbucket", label: "Bitbucket" },
  { value: "ChatGPT", label: "ChatGPT" },
  { value: "CircleCI", label: "CircleCI" },
  { value: "Eclipse", label: "Eclipse" },
  { value: "Figma", label: "Figma" },
  { value: "Git", label: "Git" },
  { value: "GitHub", label: "GitHub" },
  { value: "GitLab", label: "GitLab" },
  { value: "IntelliJIDEA", label: "IntelliJIDEA" },
  { value: "Jenkins", label: "Jenkins" },
  { value: "Jira", label: "Jira" },
  { value: "Notion", label: "Notion" },
  { value: "Postman", label: "Postman" },
  { value: "Slack", label: "Slack" },
  { value: "Swagger", label: "Swagger" },
  { value: "TravisCI", label: "TravisCI" },
  { value: "VSCode", label: "VSCode" }
];

/** 2025年時点で日常的に使われている代表的なDBをchatGPTに列挙させたリスト */
export const popularDatabases = [
  { value: "Aurora", label: "Aurora" },
  { value: "Cassandra", label: "Cassandra" },
  { value: "CloudDatastore", label: "CloudDatastore" },
  { value: "CloudSQL", label: "CloudSQL" },
  { value: "DynamoDB", label: "DynamoDB" },
  { value: "ElastiCache", label: "ElastiCache" },
  { value: "FirebaseRealtimeDatabase", label: "FirebaseRealtimeDatabase" },
  { value: "Firestore", label: "Firestore" },
  { value: "InfluxDB", label: "InfluxDB" },
  { value: "MariaDB", label: "MariaDB" },
  { value: "MongoDB", label: "MongoDB" },
  { value: "MySQL", label: "MySQL" },
  { value: "Neo4j", label: "Neo4j" },
  { value: "OracleDatabase", label: "OracleDatabase" },
  { value: "PostgreSQL", label: "PostgreSQL" },
  { value: "Redis", label: "Redis" },
  { value: "SQLite", label: "SQLite" },
  { value: "SQLServer", label: "SQLServer" }
];
